name: Build System

on:
  release:
    types: [created]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 22
      - run: npm install
        name: Install Deps
      - run: npm run executable
        name: Build Manager & Zip
      - run: npm run package
        name: Build NPM Package
      - run: npm run build:cli
        name: Build CLI
      - run: gh release upload ${{ github.event.release.tag_name }} manager.zip
        name: Upload Manager Artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish ./dist --access public -q
        name: Publish NSM package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish ./cli --access public -q
        name: Publish CLI package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
