name: Build System

on:
  release:
    types: [created]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 22
      - run: npm install
        name: Install Deps
      - run: npm run executable
        name: Build Manager & Zip
      - run: npm run package
        name: Build NPM Package
      - run: npm run build:cli
        name: Build CLI
      - uses: AButler/upload-release-assets@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: manager.zip
