name: Build System
on:
  release:
    types:
      - released

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 22
      - run: npm install
        name: Install Deps
      - run: npm run build
        name: Build
      - run: npm run package
        name: Package
      - run: npm run build:cli
        name: Build CLI
